# Generated by Django 4.2.13 on 2024-06-23 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAllowedRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=255)),
                ('view_description', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed_role', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'View Allowed Role',
                'verbose_name_plural': 'View Allowed Roles',
                'unique_together': {('view_name', 'allowed_role')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalViewAllowedRoles',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('view_name', models.CharField(db_index=True, max_length=255)),
                ('view_description', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed_role', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical View Allowed Role',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
