# Generated by Django 3.2.25 on 2024-07-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalviewallowedroles',
            name='allow_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewallowedroles',
            name='allow_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalviewallowedroles',
            name='view_name',
            field=models.CharField(max_length=255),
        ),
    ]
