# Generated by Django 3.2.25 on 2024-11-12 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eox_tenant', '0008_synchronize_tenants'),
        ('fx_helpers', '0003_clickhousequery_historicalclickhousequery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('view_name', models.CharField(max_length=255)),
                ('related_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('in_queue', 'in_queue'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='in_queue', max_length=16)),
                ('progress', models.FloatField(default=0.0)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eox_tenant.tenantconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export Task',
                'verbose_name_plural': 'Data Export Tasks',
            },
        ),
        migrations.AddIndex(
            model_name='dataexporttask',
            index=models.Index(fields=['tenant_id', 'user'], name='fx_helpers__tenant__2844f2_idx'),
        ),
        migrations.AddIndex(
            model_name='dataexporttask',
            index=models.Index(fields=['view_name', 'related_id'], name='fx_helpers__view_na_89b91b_idx'),
        ),
    ]
