# Generated by Django 3.2.21 on 2024-10-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_helpers', '0003_clickhousequery_historicalclickhousequery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=16)),
            ],
            options={
                'verbose_name': 'Data Export Task',
                'verbose_name_plural': 'Data Export Tasks',
            },
        ),
    ]
