# Generated by Django 3.2.25 on 2024-10-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_helpers', '0004_dataexporttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexporttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataexporttask',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataexporttask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataexporttask',
            name='status',
            field=models.CharField(choices=[('in_queue', 'in_queue'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='in_queue', max_length=16),
        ),
    ]
