# Generated by Django 3.2.21 on 2024-10-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_helpers', '0004_dataexporttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexporttask',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
