# Generated by Django 3.2.21 on 2024-11-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eox_tenant', '0008_synchronize_tenants'),
        ('fx_helpers', '0005_data_export_new_fields_for_error_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataexporttask',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='dataexporttask',
            name='related_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataexporttask',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eox_tenant.tenantconfig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataexporttask',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='dataexporttask',
            index=models.Index(fields=['tenant_id', 'user'], name='fx_helpers__tenant__2844f2_idx'),
        ),
        migrations.AddIndex(
            model_name='dataexporttask',
            index=models.Index(fields=['view_name', 'related_id'], name='fx_helpers__view_na_89b91b_idx'),
        ),
    ]
