# Generated by Django 4.0.10 on 2025-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_helpers', '0006_configaccesscontrol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configaccesscontrol',
            name='key_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('dict', 'Dict'), ('list', 'List')], default='string', help_text='Data type of the key', max_length=20),
        ),
    ]
