# Generated by Django 4.0.10 on 2025-05-24 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fx_helpers', '0008_historicaltenantasset_tenantasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_path', models.CharField(help_text='Dot-separated path, e.g., theme_v2.footer.linkedin_url', max_length=255)),
                ('config_value', models.TextField(blank=True, default=dict)),
                ('revision_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_config_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eox_tenant.tenantconfig')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_config_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Draft Configuration',
                'verbose_name_plural': 'Draft Configurations',
                'unique_together': {('tenant', 'config_path')},
            },
        ),
    ]
