# Generated by Django 4.0.10 on 2025-05-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_helpers', '0009_configaccesscontrol_mirror_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='configaccesscontrol',
            name='extra_mirror_path',
            field=models.CharField(blank=True, help_text='Dot-separated path, e.g., theme_v2.footer.linkedin_url', max_length=500, null=True),
        ),
    ]
