# Generated by Django 4.0.10 on 2025-06-25 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fx_helpers', '0009_draftconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConfigMirror',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('source_path', models.CharField(help_text='Dot-separated path, e.g., theme_v2.footer.linkedin_url', max_length=255)),
                ('destination_path', models.CharField(help_text='Dot-separated path, e.g., theme_v2.footer.linkedin_url', max_length=255)),
                ('missing_source_action', models.CharField(choices=[('skip', 'Skip'), ('set_null', 'Set Null'), ('delete', 'Delete'), ('copy_dest', 'Copy Destination')], default='skip', help_text='Action to take if the source is missing.', max_length=16)),
                ('priority', models.IntegerField(default=0, help_text='Priority of the mirror. Higher priority mirrors will be applied first. Similar priorities will be applied according to the id value in ascending order.')),
                ('enabled', models.BooleanField(default=False, help_text='Indicates if the mirror is enabled or not.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Config Mirror',
                'verbose_name_plural': 'historical Config Mirrors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigMirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(help_text='Dot-separated path, e.g., theme_v2.footer.linkedin_url', max_length=255)),
                ('destination_path', models.CharField(help_text='Dot-separated path, e.g., theme_v2.footer.linkedin_url', max_length=255)),
                ('missing_source_action', models.CharField(choices=[('skip', 'Skip'), ('set_null', 'Set Null'), ('delete', 'Delete'), ('copy_dest', 'Copy Destination')], default='skip', help_text='Action to take if the source is missing.', max_length=16)),
                ('priority', models.IntegerField(default=0, help_text='Priority of the mirror. Higher priority mirrors will be applied first. Similar priorities will be applied according to the id value in ascending order.')),
                ('enabled', models.BooleanField(default=False, help_text='Indicates if the mirror is enabled or not.')),
            ],
            options={
                'verbose_name': 'Config Mirror',
                'verbose_name_plural': 'Config Mirrors',
                'unique_together': {('source_path', 'destination_path')},
            },
        ),
    ]
