# Generated by Django 4.0.10 on 2026-05-20 13:32

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_helpers', '0010_historicalconfigmirror_configmirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(max_length=255, unique=True)),
                ('certificate_count_all', models.IntegerField(default=0)),
                ('certificate_count_non_staff', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
