name: Python CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  run_tests:
    name: ci
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python-version: '3.11'
            tox-env: quality
          - python-version: '3.11'
            tox-env: py311-redwood
          - python-version: '3.11'
            tox-env: py311-sumac

    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install -r requirements/ci.in

      - name: List test utils
        run: echo $PYTHONPATH

      - name: Run Tests
        run: tox -e ${{ matrix.tox-env }}
